//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siren.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siren.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potion
        ///Potion-2
        ///Hi-Potion
        ///Hi-Potion-2
        ///X-Potion
        ///Mega-Potion
        ///Phönix-Feder
        ///Mega-Phönix
        ///Elixir
        ///Final-Elixir
        ///Gegengift
        ///Goldene Nadel
        ///Augentropfen
        ///Echo-Kraut
        ///Weihwasser
        ///Mega-Pille
        ///Mega-Pille-2
        ///Heldensaft
        ///Heldentrank
        ///Göttersaft
        ///Göttertrank
        ///Shell-Stein
        ///Protes-Stein
        ///Aura-Stein
        ///Todesstein
        ///Holy-Stein
        ///Flare-Stein
        ///Meteor-Stein
        ///Ultima-Stein
        ///Gizar-Kraut
        ///Phönix-Flügel
        ///Feuer-Siegel
        ///Zelt
        ///Stall
        ///Hütte
        ///G-Potion
        ///G-Hi-Potion
        ///G-Mega-Potion
        ///G-Returner
        ///Namensschild
        ///Vergißmeinnicht
        ///HP-Buch
        ///St [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemsListDe {
            get {
                return ResourceManager.GetString("ItemsListDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potion
        ///Potion+
        ///Hi-Potion
        ///Hi-Potion+
        ///X-Potion
        ///Mega-Potion
        ///Phoenix Down
        ///Mega Phoenix
        ///Elixir
        ///Megalixir
        ///Antidote
        ///Soft
        ///Eye Drops
        ///Echo Screen
        ///Holy Water
        ///Remedy
        ///Remedy+
        ///Hero-Trial
        ///Hero
        ///Holy War-Trial
        ///Holy War
        ///Shell Stone
        ///Protect Stone
        ///Aura Stone
        ///Death Stone
        ///Holy Stone
        ///Flare Stone
        ///Meteor Stone
        ///Ultima Stone
        ///Gysahl Greens
        ///Phoenix Pinion
        ///Friendship
        ///Tent
        ///Pet House
        ///Cottage
        ///G-Potion
        ///G-Hi-Potion
        ///G-Mega-Potion
        ///G-Returner
        ///Rename Card
        ///Amnesia Greens
        ///HP-J Scroll
        ///Str-J Scroll
        ///Vit-J Sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemsListEn {
            get {
                return ResourceManager.GetString("ItemsListEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poción
        ///Poción+
        ///Ultrapoción
        ///Ultrapoción+
        ///Poción X
        ///Omnipoción
        ///Cola de Fénix
        ///Omnifénix
        ///Elixir
        ///Superelixir
        ///Antídoto
        ///Aguja de oro
        ///Colirio
        ///Hierba del eco
        ///Agua bendita
        ///Panacea
        ///Panacea+
        ///Sal heroica beta
        ///Sal heroica
        ///Sal sagrada beta
        ///Sal sagrada
        ///Piedra Coraza
        ///Piedra Escudo
        ///Piedra Aura
        ///Piedra Muerte
        ///Piedra Sanctus
        ///Piedra Fulgor
        ///Piedra Meteo
        ///Piedra Artema
        ///Verdura Gysahl
        ///Ala de Fénix
        ///Señal de lealtad
        ///Tienda de lona
        ///Caseta
        ///Chalé
        ///Poción G.F.
        ///Ultrapoción G.F.
        ///Omnipoción G.F.
        ///Resucitado [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemsListEs {
            get {
                return ResourceManager.GetString("ItemsListEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potion
        ///Potion+
        ///Hypra-Potion
        ///Maxi potion
        ///Potion totale
        ///Méga potion
        ///MT-Psy
        ///Maxi MT-Psy
        ///Elixir
        ///Mégalixir
        ///Antidote
        ///Défijeur
        ///Lasik
        ///Bocca
        ///Eau bénite
        ///Remède
        ///Remède +
        ///1-20-Syble
        ///Invulnérable
        ///1-destructible
        ///Croisade
        ///Roc cosse
        ///Roc carapace
        ///Roc d&apos;Aura
        ///Roc mortel
        ///Roc sacré
        ///Roc flamboyant
        ///Roc Météore
        ///Roc Ultima
        ///ChocoLégume
        ///Golgotha
        ///Pen Pal
        ///Red Kross
        ///Zoologie
        ///Saindoux
        ///Potion GF
        ///Potion GF +
        ///Mégapotion GF
        ///Sel marin
        ///Carte baptême
        ///Décapaciteur
        ///Livret HP-A
        ///Livret Vgr-A
        ///Livret Dfs-A
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemsListFr {
            get {
                return ResourceManager.GetString("ItemsListFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozione
        ///Pozione+
        ///Granpozione
        ///Granpozione+
        ///Extrapozione
        ///Megapozione
        ///Coda di Fenice
        ///Megafenice
        ///Elisir
        ///Megalisir
        ///Antidoto
        ///Ago Dorato
        ///Collirio
        ///Erba dell&apos;Eco
        ///Acquasanta
        ///Panacea
        ///Panacea+
        ///Med dell&apos;Eroe ß
        ///Med dell&apos;Eroe
        ///Med del Mago ß
        ///Med del Mago
        ///Gemma Shell
        ///Gemma Protect
        ///Gemma Aura
        ///Gemma Death
        ///Gemma Holy
        ///Gemma Flare
        ///Gemma Meteor
        ///Gemma Ultima
        ///Erba Ghisal
        ///Piuma di Fenice
        ///Superamico
        ///Tenda
        ///Cuccia
        ///Cottage
        ///Pozione G
        ///Granpozione G
        ///Megapozione G
        ///Rivitalizzatore G
        ///Carta d&apos;Identità
        ///Sm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemsListIt {
            get {
                return ResourceManager.GetString("ItemsListIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap siren {
            get {
                object obj = ResourceManager.GetObject("siren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
